/* export interface Trainer {
    trainerName: string,
    trainerCode: string,
    idNbr: string,
    email: string,
    dob: string,
    mobileNbr: string ,
    aboutMe: string ,
    declareChk: false,
    shareChk: false,
    highestEdu: string ,
    highestEduNote: string ,
    edu1: string ,
    edu2: string ,
    edu3: string ,
    edu4: string ,
    edu5: string ,
    edu1Note: string ,
    edu2Note: string ,
    edu3Note: string ,
    edu4Note: string ,
    edu5Note: string ,
    programs: [],
    trainCerts: [],
    trainExps: [],
    achievements: []
    } */